[paths]
use_env_json = true

[sections]
"SUMMARY" = "summary.pdf"
"NARRATIVE" = "narrative.pdf"
"REFERENCES" = "references.pdf"
"FACILITIES" = "facilities.pdf"
"EQUIPMENT" = "equipment.pdf"
"SPECIFIC AIMS" = "specific_aims.pdf"
"RESEARCH STRATEGY" = "research_strategy.pdf"
los_bundle = "los.pdf"
"RESOURCE SHARING PLAN" = "resource_sharing.pdf"
otherplan_bundle = "otherplan_dms.pdf"
"DATA MANAGEMENT AND SHARING" = "otherplan_IGNORE.pdf"
#"ADDITIONAL JUSTIFICATION" = "addtional_narrative_justification_dmsj.pdf"
budgetjust_bundle = "budget_justification.pdf"
"BUDGET JUSTIFICATION" = "budget_justification_IGNORE.pdf"  # n.b. goes in a bundle
"EXPLANATION FOR USE OF HUMAN SUBJECTS" = "s0_explanation_humans.pdf"
"INCLUSION OF INDIVIDUALS ACROSS THE LIFESPAN (STUDY 1)" = "s1_inclusion_lifespan.pdf"
"INCLUSION OF WOMEN AND MINORITIES (STUDY 1)" = "s1_inclusion_wm.pdf"
"RECRUITMENT AND RETENTION PLAN (STUDY 1)" = "s1_recruitment.pdf"
"STUDY TIMELINE (STUDY 1)" = "s1_timeline.pdf"
"PROTECTION OF HUMAN SUBJECTS (STUDY 1)" = "s1_protection_human.pdf"
"DATA AND SAFETY MONITORING PLAN (STUDY 1)" = "s1_dsm_plan.pdf"
"STRUCTURE OF THE STUDY TEAM (STUDY 1)" = "s1_structure_team.pdf"
"INCLUSION OF INDIVIDUALS ACROSS THE LIFESPAN (STUDY 2)" = "s2_inclusion_lifespan.pdf"
"INCLUSION OF WOMEN AND MINORITIES (STUDY 2)" = "s2_inclusion_wm.pdf"
"RECRUITMENT AND RETENTION PLAN (STUDY 2)" = "s2_recruitment.pdf"
"STUDY TIMELINE (STUDY 2)" = "s2_timeline.pdf"
"PROTECTION OF HUMAN SUBJECTS (STUDY 2)" = "s2_protection_human.pdf"
"DATA AND SAFETY MONITORING PLAN (STUDY 2)" = "s2_dsm_plan.pdf"
"STRUCTURE OF THE STUDY TEAM (STUDY 2)" = "s2_structure_team.pdf"
"STUDY 1 DESIGN (NOT AN ATTACHMENT)"= "s1_design_IGNORE.pdf"
"INCLUSION ENROLLMENT REPORT (STUDY 1 - NOT AN ATTACHMENT)" = "s1_inclusion_enrollment_IGNORE.pdf"
"ELIGIBILITY CRITERIA (STUDY 1 - NOT AN ATTACHMENT)" = "s1_Elegibility_criteria_IGNORE.pdf"
"STUDY 2 DESIGN (NOT AN ATTACHMENT)" = "s2_design_IGNORE.pdf"
"INCLUSION ENROLLMENT REPORT (STUDY 2 - NOT AN ATTACHMENT)" = "s2_inclusion_enrollment_IGNORE.pdf"
"ELIGIBILITY CRITERIA (STUDY 2 - NOT AN ATTACHMENT)" = "s2_Elegibility_criteria_IGNORE.pdf"
TITLE = "title_section_IGNORE.pdf"
FIGURES = "figures_section_IGNORE.pdf"
INTERNAL = "internal_section_IGNORE.pdf"

[merge]
sets = [
    { name = "science_bundle", sections = ["SUMMARY", "NARRATIVE", "SPECIFIC AIMS", "RESEARCH STRATEGY", "REFERENCES"]},
    { name = "los_bundle", sections = ["/home/mcintosh/Cloud/Other/Desktop/2026-10-05_onmep_r01_a0/standalone/los_2026-10_cu_carmel.pdf",
        "/home/mcintosh/Cloud/Other/Desktop/2026-10-05_onmep_r01_a0/standalone/los_2026-10_cu_mandigo.pdf"] },
    { name = "otherplan_bundle", sections = ["/home/mcintosh/Cloud/Other/Desktop/2026-10-05_onmep_r01_a0/standalone/other_plan_dms.pdf"] },
    { name = "budgetjust_bundle", sections = ["BUDGET JUSTIFICATION",
        "/home/mcintosh/Cloud/Other/Desktop/2026-10-05_onmep_r01_a0/wip/meta/invoices/digitimer_ds8r_Quote CU 09-30-26.pdf",
        "/home/mcintosh/Cloud/Other/Desktop/2026-10-05_onmep_r01_a0/wip/meta/invoices/emg_quote_motionlabs_page1.pdf"] }
]

[processing]
remove_hyperlinks = true
attach_string = "datetime"
science_keys = [
    "FACILITIES", "EQUIPMENT", "BUDGET JUSTIFICATION", "RESOURCE SHARING PLAN",
    "DATA MANAGEMENT AND SHARING", "ELIGIBILITY CRITERIA", "INCLUSION OF INDIVIDUALS ACROSS THE LIFESPAN",
    "INCLUSION OF WOMEN AND MINORITIES", "RECRUITMENT AND RETENTION PLAN", "PROTECTION OF HUMAN SUBJECTS",
    "DATA AND SAFETY MONITORING PLAN", "STRUCTURE OF THE STUDY TEAM"
]
